### ISSUE TITLE
Development: Unable to perform npm install in dependencies folder

### ISSUE THREAD

**Issue by nvuillam** [github/super-linter#538] opened 2020-08-08 07:12 UTC
**Describe the bug**
There is a crash in sql-lint post install task when performing `npm install` in dependencies folder
Env: Windows 10 + Git Bash

**To Reproduce**
1. Clone master branch
2. cd dependencies
3. npm install

**Expected behavior**
npm install should work :)

**Screenshots**
![image](https://user-images.githubusercontent.com/17500430/89704737-e3c56200-d956-11ea-8791-f53ce3b902af.png)

**Comment by IAmHughes** [comment] 2020-08-08 14:00
I was able to reproduce this, but  we don't own the `sql-lint` package, and this seems to be a problem with the package itself not `super-linter`.

I'd encourage you to open an issue [on their repo](https://github.com/joereynolds/sql-lint) with the bug information. I'm going to close this one as `wontfix`, but if you hear back from them that the project using the package is doing something wrong, please ask for this to be re-opened and link to the comment ❤️

**Closed by IAmHughes** 2020-08-08 14:00 UTC
Labels: bug

**Comment by nvuillam** [comment] 2020-08-08 17:10
I know it's a sql-lint problem, but should a package be used if it is not compliant with all platforms ?

Letting this dependency will prevent any windows user to make PRs to super-linter... is that really what you want 🥺 or could we remove this broken package until it's fixed ?

Note: I noticed this crash when trying to upgrade npm-groovy-lint to its latest version 🌞

**Comment by IAmHughes** [comment] 2020-08-10 13:37
@nvuillam the package states it supports Windows in [the documentation](https://sql-lint.readthedocs.io/en/latest/files/installation.html). Again, I encourage you to [open an issue](https://github.com/joereynolds/sql-lint/issues/new) on the `sql-lint` repo about this, I see you haven't yet. That developer seems pretty responsive.

Please understand we can't be responsible for ensuring every package that we use works on all platforms all the time.

**Comment by nvuillam** [comment] 2020-08-10 16:11
@IAmHughes > Done :) https://github.com/joereynolds/sql-lint/issues/157

But as it seems we are a lot of contributors on super-linter, maybe we could add in the PR jobs a test on Windows ?  👼

**Comment by IAmHughes** [comment] 2020-08-10 16:17
> maybe we could add in the PR jobs a test on Windows

Since this is Docker, can you try using Docker for Windows for your development? It's possible, but in general it's a bit of an anti-pattern to write tests to ensure functionality of packages you don't own. i.e. if we required `google.com` functionality, I don't really write tests against `google.com` because Google is responsible for testing that and providing a service. We consume what they say they offer (in the case of the `sql-lint` it supports Windows per their docs).

I hear the point for sure, but I discussed with some other maintainers here as well and testing dependencies' functionalities isn't a good pattern for us to follow.

**Comment by nvuillam** [comment] 2020-08-10 16:29
I'm not talking about testing dependencies, just about testing that those dependencies ... can be installed :)

With just a `npm ci` in a windows env, the person who added sql-lint would have seen the issue with a nice red flag on its PR, and ot wouldn't be for us to solve this issue 😁

I'm new to github actions, but i know how to do it with Circle CI so it must not be so difficult with a GH action (if they natively support windows images 😁)

I'll try to have a look 🤓

**Comment by GaboFDC** [comment] 2020-08-10 17:31
@nvuillam why are you trying to install the dependencies on windows?
I think the lack of a test on a windows platform is because is not really a use case, the container is built under a Linux environment. Building it under windows I think will arise a lot more errors and don't see any point of benefit on doing it.

**Comment by nvuillam** [comment] 2020-08-10 17:37
I develop on Windows, and I need to upgrade npm-groovy-lint

To do that, I just forked the repo then run `npm install npm-groovy-lint --save` , but as it crashes because of install of sql-lint, I can't :)

I could manually update package.json, but I have no idea about how to update package-lock.json without risking pf breaking something 😇

**Comment by nvuillam** [comment] 2020-08-11 16:40
@IAmHughes  PR submitted 😃 

https://github.com/github/super-linter/pull/554
