### ISSUE TITLE
"Failed to call GitHub Status API" with blank errors.

### ISSUE THREAD

**Issue by Zee2** [github/super-linter#3137] opened 2022-07-12 00:05 UTC
## Describe the bug

Trying to setup `super-linter` and I can't get it to report statuses correctly, and I'm also getting these mysterious status API failures.

```
2022-07-11 23:53:51 [INFO]   ERROR! Failed to call GitHub Status API!
2022-07-11 23:53:51 [INFO]   ERROR:[]
2022-07-11 23:53:51 [INFO]   ERROR! Failed to call GitHub Status API!
2022-07-11 23:53:51 [INFO]   ERROR:[]
2022-07-11 23:53:52 [INFO]   ERROR! Failed to call GitHub Status API!
2022-07-11 23:53:52 [INFO]   ERROR:[]
2022-07-11 23:53:52 [INFO]   ERROR! Failed to call GitHub Status API!
2022-07-11 23:53:52 [INFO]   ERROR:[]
2022-07-11 23:53:52 [INFO]   ERROR! Failed to call GitHub Status API!
2022-07-11 23:53:52 [INFO]   ERROR:[]
```

I am passing in the token correctly with `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`.

## Expected behavior

The status is set correctly and no Status API errors appear.

## Steps to Reproduce

My workflow file looks like:

```
name: Lint
on:
  push:
    branches: ["foobar"]
  pull_request:
    branches: ["foobar"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    
    - name: Lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: foobar
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Additional context

Possibly related to #556?

**Comment by Zee2** [comment] 2022-07-12 00:08
Ah, same as #2641, too!

**Comment by Zee2** [comment] 2022-08-11 04:13
This is still an issue for us :(

**Comment by Zee2** [comment] 2022-09-12 18:30
Still an issue....

**Comment by sid-am-ahd935** [comment] 2022-09-20 08:09
Any workarounds for this??

**Comment by ferrarimarco** [comment] 2022-09-27 16:59
Hi! To troubleshoot this issue, we need to be able to reproduce it. Can you please provide an example of a source file that triggers this?

**Comment by eitsupi** [comment] 2022-09-28 08:47
I have been using supler-linter for the past several months and have rarely seen this error not occur and occur in most cases.
rocker-org/rocker-versioned2#516

The source code being linted did not appear to be related to the error (i.e., the error may or may not have occurred in the same PR).
(That is, there were cases where the error did not occur within the same PR, but the cases where the error did not occur were so rare that I forgot which PR it was.)

**Comment by ferrarimarco** [comment] 2022-09-28 11:21
I suspect it's some kind of transient error. Given that we didn't enable `--show-error` but we did enable silent mode when using `cURL` to call the status API, we aren't going to get any output to investigate. I'm going to add the `--show-error` in #3367 with the hope that the curl error output gives us some hints about what went wrong.

**Comment by ferrarimarco** [comment] 2022-09-30 18:23
@Zee2 now that we merged #3367, we're going to get more detailed output. I'm going to close this one, but please open a new issue once you're able to reproduce this, or to get any output. I'll keep an eye on this as well.

**Closed by ferrarimarco** 2022-09-30 18:23 UTC
Labels: bug, O: backlog 🤖

**Comment by Zee2** [comment] 2022-09-30 23:48
@ferrarimarco , thanks so much for taking a look at this and responding. I'll give it another whirl and see what happens.

**Comment by eitsupi** [comment] 2022-10-01 03:57
https://github.com/rocker-org/website/pull/72/checks#step:4:122

It doesn't look like anything has changed to me.

**Comment by Zee2** [comment] 2022-10-04 20:36
Alrighty! @ferrarimarco , it's failing w/ an HTTP 403.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/5544935/193921917-2635bd9a-8a4d-49e9-81a0-fe092acc55fc.png">

**Comment by Zee2** [comment] 2022-10-04 20:44
@ferrarimarco followup is here: https://github.com/github/super-linter/issues/3419

**Comment by ferrarimarco** [comment] 2022-10-05 07:55
@Zee2 Can you also share the list of permissions that `GITHUB_TOKEN` has? They should be listed at the beginning of the workflow log. I suspect this could be due to the fact that `GITHUB_TOKEN` doesn't have `write` access to the Status API.

**Comment by shaneholloman** [comment] 2024-02-05 05:24
still an issue in v5

```yml
name: superlint

'on':
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSCPD: false
          VALIDATE_POWERSHELL: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          FILTER_REGEX_EXCLUDE: docker-compose/.env
          # This excludes the .env file from being linted on purpose since it is an example file only
```

```log
2024-02-05 05:04:05 [INFO]   File:[/github/workspace/templates/unpackerr.yml]
2024-02-05 05:04:05 [INFO]    - File:[unpackerr.yml] was linted with [yamllint] successfully
2024-02-05 05:04:05 [INFO]   ----------------------------------------------
2024-02-05 05:04:05 [INFO]   ----------------------------------------------
2024-02-05 05:04:05 [INFO]   The script has completed
2024-02-05 05:04:05 [INFO]   ----------------------------------------------
2024-02-05 05:04:05 [INFO]   ----------------------------------------------
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
2024-02-05 05:04:06 [INFO]   ERROR! Failed to call GitHub Status API!
2024-02-05 05:04:06 [INFO]   ERROR:[curl: (22) The requested URL returned error: 403]
```

**Comment by jasonkarns** [comment] 2024-06-06 12:35
And v6
