### ISSUE TITLE
Support non-master default branches

### ISSUE THREAD

**Issue by jdyke** [github/super-linter#145] opened 2020-06-18 19:46 UTC
**Is your feature request related to a problem? Please describe.**
When setting up the linter to run as a github action, it is looking for the `master` branch but ours is named `main`. Fails with error:

```
Failed to switch to master branch to get files changed!
ERROR:[error: pathspec 'master' did not match any file(s) known to git]
```

**Describe the solution you'd like**
An environment variable could be used to input the name of the `default` branch if it is not named `master`.

**Comment by Hanse00** [comment] 2020-06-18 20:11
@admiralAwkbar I'd like to work on this one, seems like a no brainer idea (And like 10 lines of code)

**Comment by admiralAwkbar** [comment] 2020-06-18 21:44
@Hanse00 make it so...

**Comment by drewish** [comment] 2020-06-19 16:12
#152 was merged so seems like this could be closed.

**Comment by jdyke** [comment] 2020-06-19 16:16
Let me take a look. I tried earlier today and it was still failing even w/ the env var set:

```
  env:
    VALIDATE_ALL_CODEBASE: false
    VALIDATE_PYTHON: true
    DEFAULT_BRANCH: main
```

`/usr/bin/docker run --name githubsuperlinterv200_ef3398 --label 3888d3 --workdir /github/workspace --rm -e VALIDATE_ALL_CODEBASE -e VALIDATE_PYTHON -e DEFAULT_BRANCH`

**Comment by jdyke** [comment] 2020-06-19 16:19
Looks like #160 is what merged this code into `master` 

I just failed again - is anyone able to get this working? Here is my linter.yml

```
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.0.0
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true 

```

**Comment by Apreche** [comment] 2020-06-19 16:34
I have a yml basically identical to what @jdyke has and am getting the same pathspec error.

**Comment by jdyke** [comment] 2020-06-19 16:38
I assumed the new docker image wasn't published yet and was going to give it a couple hours before commenting but I didn't want this to get closed.

**Comment by Hanse00** [comment] 2020-06-19 16:55
Using `docker inspect` to see the environment variables exposed by the various versions, I can tell that `github/super-linter:latest` contains the changes above, `github/super-linter:v2.0.0` does *not*.

I'm going to defer to @zkoppert and @admiralAwkbar on what their process is here. You could probably update your yaml file to use latest, or they might have a specific versioning strategy in mind.

**Comment by jdyke** [comment] 2020-06-19 17:29
Switching to latest gives an error:
```
--------------------------------------------
Gathering user validation information...
- Only validating [new], or [edited] files in code base...
awk: cmd. line:1: Unexpected end of string

----------------------------------------------
```

**Comment by zkoppert** [comment] 2020-06-19 17:40
We need to put some automation behind versioning. I will try to cut a new release version later today.

**Comment by Hanse00** [comment] 2020-06-19 18:19
@zkoppert Do you think the error by @jdyke above has to do with how we release this? Or is it a code bug?

It's a little hard since I cannot test the changes that require the container to run in the context of a GitHub Action. Don't know if we have a solution to that :)

**Comment by zkoppert** [comment] 2020-06-19 19:09
@Hanse00 We just cut a new release so we could have @jdyke try that out first and see if the issue persists. Then we can debug from there if needed.

**Comment by jdyke** [comment] 2020-06-19 19:34
@zkoppert what would you like me to point to? 

```
################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:latest
```

**Comment by zkoppert** [comment] 2020-06-19 19:38
Yeah that will work as well as calling out v2.1.0

**Comment by jdyke** [comment] 2020-06-19 19:47
Here is what I see:

```
--------------------------------------------
Gathering user validation information...
- Only validating [new], or [edited] files in code base...
awk: cmd. line:1: Unexpected end of string
awk: cmd. line:1: Unexpected end of string
```

You can see the results here:
https://github.com/ScaleSec/gcp_api_key_inventory/pull/3/checks?check_run_id=789267373

**Comment by Hanse00** [comment] 2020-06-19 20:05
@jdyke Could you add `ACTIONS_RUNNER_DEBUG=true` to your configuration?

**Comment by jdyke** [comment] 2020-06-19 20:11
Sure thing,

https://github.com/ScaleSec/gcp_api_key_inventory/pull/3/checks?check_run_id=789354262

**Comment by Hanse00** [comment] 2020-06-19 22:38
Okay so far I've found:

* The error is present in v2.1.0, but not v2.0.0.
* The error messages from awk are presented no matter if the default branch is switched, in fact none of the environment variables need to be present for the errors to be presented (I've tried with `VALIDATE_ALL_CODEBASE` on and off, and with a few different combinations of other variables.

At this point I'm not confident if it's actually my change that is causes the problem, or something else that was merged in as well. But I'll keep digging for a bit.

**Comment by Hanse00** [comment] 2020-06-19 23:14
Finally figured out the issue, the new additions of ENV and CSS listing were missing some closing curly brackets :) That should be fixed once #206 is merged in.

**Comment by zkoppert** [comment] 2020-06-20 05:42
Merged #206 but will have to wait for @admiralAwkbar to cut a new release.

**Comment by admiralAwkbar** [comment] 2020-06-20 11:54
@zkoppert I can make a 2.1.1 right now, should we back Port this into 2.0.0 and 2.1.0?

**Comment by admiralAwkbar** [comment] 2020-06-20 12:28
@zkoppert just pushed `v2.1.1` with the fix

this has to do with the release and how we test. I will spend some time on this next week to update... my bad for the miss on this

**Comment by Apreche** [comment] 2020-06-20 13:52
I can confirm that 2.1.1 fixes the problem.

**Closed** 2020-06-20 15:19 UTC
Labels: enhancement
