### ISSUE TITLE
Is there any way to cache the docker image?

### ISSUE THREAD

**Issue by wangwalton** [github/super-linter#376] opened 2020-07-05 23:15 UTC
I'm using the following, it generally takes 1 minute to pull and build the image,
```
    - name: Super-Linter
      uses: docker://github/super-linter:v3
```

Is there any way I can do this faster by caching the docker image with github.com/actions/cache or https://github.com/marketplace/actions/build-docker-images-using-cache?

I tried with the latter docker cache, but got stuck at 
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
```

**Comment by admiralAwkbar** [comment] 2020-07-06 14:42
@wangwalton that's a great question... as we add more language support, it seems the time goes up and up...
Reaching out to internal hosting to see what our options are :)

**Comment by admiralAwkbar** [comment] 2020-07-06 14:50
@wangwalton Another option would be to host the GitHub runner and have the image cloned to the machine already :)
this would bring down your costs, as well as speed up the process :)

**Comment by nemchik** [comment] 2020-07-06 19:42
Speaking of how long it takes, are actions having some kind of service disruption? A bunch of builds on PRs seem to be hung waiting to start.

**Comment by mrchief** [comment] 2020-07-06 22:38
Or maybe pull layers based on languages to be validated. So if user specifies only JS, Ruby, pull only those containers?

**Comment by leviem1** [comment] 2020-07-08 07:06
This is actually a pretty interesting issue.

Following the instructions in README told me to use the docker image directly in my action. (Should that documentation be updated for GitHub actions?) This brings down runtime tons since we're just pulling the image, but using the GitHub action triggers a rebuild if I'm correct. Not sure what can be done about this on super-linter's end.

Unfortunately, if you use dependabot to update your actions, the docker image won't be bumped if you use that method. Luckily, docker updating is on dependabot's to-do.

**Comment by GaboFDC** [comment] 2020-07-15 14:51
Caching the docker image is more on the GitHub actions end than the action itself. Something related is https://github.com/actions/cache/issues/31 but seems like there is no current plan for the cache action to be used with docker at the moment but in the comments, there are some examples of community actions that can be used for this

**Comment by zkoppert** [comment] 2020-07-16 14:16
Confirmed with GitHub staff on the actions feature, not really any great options regarding caching right now. Re-architecture is still an option to use multiple containers but I will direct that conversation to #7 . Closing this issue for now until another solution is available.

**Closed by zkoppert** 2020-07-16 14:16 UTC
Labels: question

**Comment by peckjon** [comment] 2023-03-27 17:25
Resurfacing this, as docker step time is over 1:40 in many cases now. This alone warrants prioritization, given its widespread usage.

**Comment by steezeburger** [comment] 2024-04-23 22:54
I'm only linting Go and Markdown. I was able to reduce action time from 2:02 to :44 with https://github.com/marketplace/actions/markdownlint-cli and https://github.com/golangci/golangci-lint-action for anyone else considering a switch.

**Comment by leviem1** [comment] 2024-04-23 23:16
@steezeburger I definitely agree. I think this project is a solution looking for problems, or maybe only a problem that GitHub has with legacy codebases with many languages needing to meet some compliance guidelines. I don't think this is a typical case anymore for most users, at least for new projects. I was a pretty early adopter of this and quickly lost the ability to justify the crazy run times this image introduces. Using a purpose-built community action for the language(s) your project uses seems like the best "Keep It Simple, Stupid" option unless you have use 5+ languages.

**Comment by steezeburger** [comment] 2024-04-23 23:23
@leviem1 yeah I totally see the value if you're running a large monorepo with many langs!

**Comment by echoix** [comment] 2024-04-23 23:35
If only it was possible to use the containerd container store at the time the docker image is downloaded from a docker-based GitHub Action (before any step is able to run), it would allow to create a content-addressable docker image. That is, allowing eStargz images or zstd-chunked, or other advanced image compression. 
But why would it be ideal for this?
Using eStargz images allows to just run an image without having finished pulling it, or pulling it at all, and pull the parts/files as needed. That would mean that a carefully built image would allow for users not using certain linters to not have to pay the impact for tools they don't use. For eStargz images at least, if lazy-pulling isn't supported, it still remains a valid image that can be pulled as a whole by other clients (docker, podman, etc). 


Over at a similar tool, Megalinter, it's been almost a year that we have been giving that idea, but at the time, the docker versions available didn't allow this yet. I think that now it might be possible for us to do a workaround by changing the action type from a docker-based action to a mnemonic action that would run docker, and if a user has containerd enabled before the action calling docker runs, it would support lazy pulling the image. But it would probably overall delay the start of the linting, so we didn't implement it yet, waiting for the GitHub infrastructure to catch up.
