### ISSUE TITLE
Why does Versioning not work?

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#708] opened 2020-09-10 12:29 UTC
**Describe the bug**
There is [a bug in v3.10.0](https://github.com/github/super-linter/issues/704) so I have not upgraded to this version so am still running 3.9.4.

I still hit the bug.

**To Reproduce**

1. Setup an action with node_modules and lock the version: `uses: github/super-linter@v3.9.4`
2. Lint a repo with a `node_modules` folder. Note this folder gets linted when it previously didn't

**Expected behavior**
Versions should lock the code for stability. It's pointless using version numbers if they are ignored and latest is always run.

**Screenshots**
Example run: https://github.com/HTTPArchive/almanac.httparchive.org/pull/1062/checks?check_run_id=1095951259
As can be seen it's running v3.9.4 but is showing the bug from 3.10.0

**Additional context**
This has been going on a while but annoyed me enough to raise a separate issue for this.

**Comment by zhenik** [comment] 2020-09-10 14:51
I faced a similar issue. I would like to add a comment.

Why in the example run, version setup is explicit, but logs show that version `v3` is in use instead v3.9.4?

## Setup version explicit
<img width="1133" alt="Screenshot 2020-09-10 at 16 44 36" src="https://user-images.githubusercontent.com/15572799/92748392-617cf300-f385-11ea-86b0-8054964677e8.png">

## Log
<img width="1223" alt="Screenshot 2020-09-10 at 16 45 06" src="https://user-images.githubusercontent.com/15572799/92748444-72c5ff80-f385-11ea-8a50-675b019ce58d.png">

## Image taken with tag `v3`
<img width="877" alt="Screenshot 2020-09-10 at 16 45 58" src="https://user-images.githubusercontent.com/15572799/92748506-840f0c00-f385-11ea-9835-49ec6f389b9c.png">

**Comment by admiralAwkbar** [comment] 2020-09-10 16:23
@bazzadp I might need some help with the versioning code... seems it's not doing exactly what I would have expected

**Comment by bazzadp** [comment] 2020-09-10 16:32
Happy to help test here. Other than that dunno how it works (or how it’s supposed to anyway!) so not sure I can help fix it.

**Comment by bazzadp** [comment] 2020-09-11 11:34
Is there any chance of doing a 3.10.1 release while we wait for this to be resolved? #704 is causing us a lot of noise because of the combination of that and this bug. So I would rather get that fix out there with the existing "auto upgrade" and then fix this in a following release.

Worse case to me would be fixing this and then releasing both together, as then old branches from all our maintainers would be locked into the broken version, until they merged from main again and picked up the new version.

**Comment by ferrarimarco** [comment] 2020-09-11 16:15
I think this is a duplicate of #655

**Comment by bazzadp** [comment] 2020-09-11 16:44
> I think this is a duplicate of #655 (or related at least)

Possibly, but not convinced.

I'd expect the following to both be true:
1. Versions above v3.6.0 would fail
2. Locking to v3.6.0 would avoid any bugs introduced in v3.10.0

But neither is true.

**Comment by tbeaugrand** [comment] 2020-09-17 08:36
I think the problem is due to the hardcoded version in action.yml file

```
image: 'docker://github/super-linter:v3'
```

**Comment by bazzadp** [comment] 2020-09-17 08:42
@tbeaugrand do you mean this action.yml file?

https://github.com/github/super-linter/blob/58d3d191b823648aeb2610568a29b31ee86e895d/action.yml#L5-L6

Because the syntax is slightly different than you gave.

**Comment by tbeaugrand** [comment] 2020-09-17 08:51
@bazzadp yes sorry, i edited my post.

It was a copy from previous commit

**Comment by tbeaugrand** [comment] 2020-09-17 17:00
@zkoppert why have you hardcoded this version ?

**Comment by bazzadp** [comment] 2020-10-18 10:29
Keep open please, unless explicitly planning not to support this, as I’d still like to explicitly lock the version and only upgrade when dependabot notifies me and gives me the choice. Especially given a few broken releases like those mentioned above.

**Comment by bazzadp** [comment] 2020-11-02 23:11
I see we've released another bug in #938 breaking all linting on anyone using this project. Can we please look at this issue and introduce proper versioning to avoid this?

**Comment by dec5e** [comment] 2020-11-03 09:06
I've proposed a fix for described issue in #947.

**Comment by dec5e** [comment] 2020-11-04 07:20
> I've proposed a fix for described issue in #947.

This proposed solution doesn't work. It seems at the moment the only option to fix versioning is to have versioned `action.yaml` with hardcoded image tag

**Comment by dec5e** [comment] 2020-11-06 12:36
@admiralAwkbar Could put more attention to this issue? It's really important to have an option to use specific super-linter version without "workarounds". There was recently the "outage" for super-linter because of #938 and the only option to fix it was to switch to docker image with locked tag. That shouldn't be a recommended way.

It seems there is no simple way to make versioning work. In my PR #947 I tried to omit docker tag, expecting action's version to be passed to the image as an image tag but that didn't work. 

And as said the same PR: it would be nice if `super-linter` and `Actions` teams inside Github will join forces and find a good way to fix versioning for this [and other docker] actions. As I see it, ideal solution would automatically pass action's version as docker tag with simple syntax or even automatically. Don't know how difficult is this if possible at all. Other option I see requires building an automated workflow of updating `action.yaml` with hardcoded docker tag before publishing a new action's versions.

**Comment by admiralAwkbar** [comment] 2020-11-16 19:37
@dec5e Hey! I agree... it has been hard to get some time on this issue but I will try to find some internal help at GitHub from the Actions team and see if there is something better we can be doing. 

Sorry for the outages that have been caused, we're working on more testing and better vetting of the source.

**Comment by bazzadp** [comment] 2020-12-17 00:37
Please keep open

**Comment by ahmadnassri** [comment] 2021-01-01 20:26
@admiralAwkbar curious if you've heard from anybody within GitHub about this? also happy new year!

**Comment by admiralAwkbar** [comment] 2021-01-04 15:13
@ahmadnassri We updated the build process before break and I'm wondering if this has fixed the issue?

can you try to see if all is working as expected now?

**Comment by ahmadnassri** [comment] 2021-01-04 17:37
@admiralAwkbar the linting issue which resulted in the errors at the time is fixed yes, however I'm still curious about Docker based Actions versioning ... not being able to use a "fixed" version is still a problem!

**Comment by ahmadnassri** [comment] 2021-01-28 19:41
Linking to #490 as well

**Comment by zkoppert** [comment] 2021-01-30 04:44
consolidating this issue into #490. Let's continue the discussion there.

**Closed by zkoppert** 2021-01-30 04:44 UTC
Labels: bug
