### ISSUE TITLE
[FATAL]     -> ANSIBLE_LINTER_RULES rules file () doesn't exist. Terminating...

### ISSUE THREAD

**Issue by markti-beyondtrust** [github/super-linter#939] opened 2020-11-02 19:27 UTC
**Describe the bug**
2020-11-02 19:21:24 [FATAL]     -> ANSIBLE_LINTER_RULES rules file () doesn't exist. Terminating...

**To Reproduce**

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Expected behavior**
We don't have any ansible code, ansible linter should find no files and exit silently

**Additional context**
We've been running this action on a codebase with the following files:

- Docker
- YML
- C#

**Comment by admiralAwkbar** [comment] 2020-11-02 19:34
@markti-beyondtrust 
That's odd that the file name is empty...

Can you run it with flag
```yml
ACTIONS_RUNNER_DEBUG: true
```

And send the details?

**Comment by denis-matchenko** [comment] 2020-11-02 19:36
same issue https://github.com/github/super-linter/issues/938

**Comment by dshevtsov** [comment] 2020-11-02 19:49
similar issue [here](https://github.com/magento/devdocs/pull/8169/checks?check_run_id=1344010859)

**Comment by ferrarimarco** [comment] 2020-11-02 20:09
Duplicate of #938

**Closed by ferrarimarco** 2020-11-02 20:09 UTC
Labels: bug, duplicate
