### ISSUE TITLE
all the versions are serving the same image

### ISSUE THREAD

**Issue by ahmadnassri** [github/super-linter#943] opened 2020-11-03 01:34 UTC
**Describe the bug**

seemingly all versions are serving the same actual image, regardless of described version number in workflow file

**Screenshots**

###### `@v3`

![image](https://user-images.githubusercontent.com/183195/97936819-c253f680-1d4a-11eb-9dd3-e506984b0790.png)

###### `@v3.13.2`

![image](https://user-images.githubusercontent.com/183195/97936832-ca139b00-1d4a-11eb-96a5-39b0c31bd595.png)

###### `@v3.13.1`

![image](https://user-images.githubusercontent.com/183195/97936849-d26bd600-1d4a-11eb-8e03-1619bf9c0ffa.png)

**Additional context**

discovered this while trying to roll back due to #938

**Comment by TomerFi** [comment] 2020-11-03 08:36
Perhaps [this](https://github.com/github/super-linter/blob/v3.13.3/action.yml#L6) is the reason.
I've followed git blame for that line, it was always the case.

**Comment by TomerFi** [comment] 2020-11-03 08:45
https://github.com/github/super-linter/issues/938#issuecomment-720977157 offers a tested workaround for pinning the version regardless.

**Comment by bazzadp** [comment] 2020-11-03 10:09
Duplicate of #708

**Comment by ahmadnassri** [comment] 2020-11-03 15:50
indeed @TomerFi this seems like GtiHub Actions itself being .... not great in their definitions of `action.yml`...

if that line is removed, github actions willl attempt to pull and build the super-linter image in your own workflow !

**Comment by ahmadnassri** [comment] 2020-12-04 00:31
commenting so this issue doesn't get marked as stale

**Comment by ahmadnassri** [comment] 2021-01-12 20:27
marking this is as not stale, alsow discussed in #708 ... perhaps a merge of issues is needed.

regardless, issue is still ocurring.

**Comment by zkoppert** [comment] 2021-01-30 04:41
closing this as a duplicate of #708. Please continue the discussion there.

**Closed by zkoppert** 2021-01-30 04:41 UTC
Labels: bug
